name: build

on:
  push:
    branches: ['*']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
      # - run: yarn test
      - run: yarn build:chrome
      - name: Upload artifact `gas-tracker-chrome`
        uses: actions/upload-artifact@v3
        with:
          name: gas-tracker-chrome
          path: build
      - run: yarn build:firefox
      - name: Upload artifact `gas-tracker-firefox`
        uses: actions/upload-artifact@v3
        with:
          name: gas-tracker-firefox
          path: build
      - run: yarn build
      - name: Telegram Failure Notification
        uses: appleboy/telegram-action@v0.1.1
        if: failure()
        with:
          message: ❗ Build failed for [${{ github.repository }}](https://github.com/${{ github.repository }}/actions) because of [${{ github.actor }}](https://github.com/${{ github.actor }})
          format: markdown
          disable_web_page_preview: true
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set vars
        id: vars
        run: |
          echo "::set-output name=tag::$(echo $GITHUB_REF_NAME | sed -e 's/^master$/latest/')"
          echo "::set-output name=repo_name::$(echo ${GITHUB_REPOSITORY#*/})"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }}

      - uses: nrwl/last-successful-commit-action@v1
        id: last_successful_commit
        with:
          branch: 'master'
          workflow_id: 'build.yml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Format changelog
        id: changelog
        run: |
          STR="$(git log --pretty=format:'• %s' ${{ steps.last_successful_commit.outputs.commit_hash }}..HEAD)"
          STR="${STR//'%'/'%25'}"
          STR="${STR//$'\n'/'%0A'}"
          STR="${STR//$'\r'/'%0D'}"
          STR="%0D%0A$STR"
          echo "::set-output name=changelog::$STR"

      - name: Telegram Notification
        uses: appleboy/telegram-action@v0.1.1
        with:
          message: 🚀 Published a [${{ steps.vars.outputs.repo_name }}](https://github.com/${{ github.repository }}) to [GitHub registry](https://github.com/${{ github.repository }}/pkgs/container/${{ steps.vars.outputs.repo_name }})${{steps.changelog.outputs.changelog}}
          format: markdown
          disable_web_page_preview: true
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: Telegram Failure Notification
        uses: appleboy/telegram-action@v0.1.1
        if: failure()
        with:
          message: ❗ Failed to publish [${{ steps.vars.outputs.repo_name }}](https://github.com/${{ github.repository }}/actions) because of [${{ github.actor }}](https://github.com/${{ github.actor }})
          format: markdown
          disable_web_page_preview: true
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
